# Generated by Django 5.1.7 on 2025-03-22 08:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('server_uri', models.CharField(max_length=255, verbose_name='服务器URI')),
                ('bind_dn', models.CharField(max_length=255, verbose_name='绑定DN')),
                ('bind_password', models.CharField(max_length=255, verbose_name='绑定密码')),
                ('base_dn', models.CharField(max_length=255, verbose_name='基础DN')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='使用SSL')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'LDAP配置',
                'verbose_name_plural': 'LDAP配置',
            },
        ),
        migrations.CreateModel(
            name='SyncConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='配置名称')),
                ('sync_type', models.CharField(choices=[('wecom', '企业微信'), ('feishu', '飞书'), ('dingtalk', '钉钉')], max_length=20, verbose_name='同步类型')),
                ('sync_users', models.BooleanField(default=True, verbose_name='同步用户')),
                ('sync_departments', models.BooleanField(default=True, verbose_name='同步部门')),
                ('user_ou', models.CharField(default='users', max_length=255, verbose_name='用户OU')),
                ('department_ou', models.CharField(default='departments', max_length=255, verbose_name='部门OU')),
                ('sync_frequency', models.CharField(choices=[('realtime', '实时同步'), ('hourly', '每小时'), ('daily', '每天'), ('weekly', '每周'), ('manual', '手动')], default='manual', max_length=20, verbose_name='同步频率')),
                ('last_sync_time', models.DateTimeField(blank=True, null=True, verbose_name='上次同步时间')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ldap_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sync.ldapconfig', verbose_name='LDAP配置')),
            ],
            options={
                'verbose_name': '同步配置',
                'verbose_name_plural': '同步配置',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='同步时间')),
                ('success', models.BooleanField(default=False, verbose_name='是否成功')),
                ('message', models.TextField(blank=True, verbose_name='同步消息')),
                ('users_synced', models.IntegerField(default=0, verbose_name='同步用户数')),
                ('departments_synced', models.IntegerField(default=0, verbose_name='同步部门数')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='sync.syncconfig', verbose_name='同步配置')),
            ],
            options={
                'verbose_name': '同步日志',
                'verbose_name_plural': '同步日志',
                'ordering': ['-sync_time'],
            },
        ),
    ]
