# Generated by Django 5.1.7 on 2025-03-23 03:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('create', '新增'), ('update', '更新'), ('move', '移动'), ('delete', '删除')], max_length=20, verbose_name='操作类型')),
                ('object_type', models.CharField(choices=[('user', '用户'), ('department', '部门')], max_length=20, verbose_name='对象类型')),
                ('object_id', models.CharField(max_length=255, verbose_name='对象ID')),
                ('object_name', models.CharField(max_length=255, verbose_name='对象名称')),
                ('object_dn', models.CharField(max_length=512, verbose_name='对象DN')),
                ('details', models.TextField(blank=True, verbose_name='详细信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sync_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sync.synclog', verbose_name='同步日志')),
            ],
            options={
                'verbose_name': '同步详情',
                'verbose_name_plural': '同步详情',
                'ordering': ['created_at'],
            },
        ),
    ]
