# Generated by Django 5.1.7 on 2025-03-23 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_syncdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SyncDetail',
        ),
    ]
