# Generated by Django 5.1.7 on 2025-03-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0004_synclog_detail_log_alter_synclog_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synclog',
            name='detail_log',
        ),
        migrations.AddField(
            model_name='synclog',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='详细同步记录'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='message',
            field=models.TextField(blank=True, default='1', verbose_name='同步消息'),
            preserve_default=False,
        ),
    ]
