# Generated by Django 5.1.7 on 2025-03-23 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0005_remove_synclog_detail_log_synclog_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synclog',
            name='details',
        ),
    ]
