# Generated by Django 5.1.7 on 2025-03-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0006_remove_synclog_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
