# Generated by Django 5.1.7 on 2025-03-23 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0007_synclog_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synclog',
            name='details',
        ),
    ]
