# Generated by Django 5.1.7 on 2025-03-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0008_remove_synclog_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='detail_log',
            field=models.TextField(blank=True, default='', help_text='详细的同步操作日志，包含字段级别的变更'),
        ),
    ]
