# Generated by Django 5.1.7 on 2025-03-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0009_synclog_detail_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synclog',
            name='detail_log',
        ),
    ]
