# Generated by Django 5.1.7 on 2025-03-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0010_remove_synclog_detail_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='departments_added',
            field=models.IntegerField(default=0, verbose_name='新增部门数'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='departments_deleted',
            field=models.IntegerField(default=0, verbose_name='删除部门数'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='departments_moved',
            field=models.IntegerField(default=0, verbose_name='移动部门数'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='departments_updated',
            field=models.IntegerField(default=0, verbose_name='更新部门数'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='detailed_logs',
            field=models.JSONField(blank=True, default=dict, verbose_name='详细操作日志'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='users_added',
            field=models.IntegerField(default=0, verbose_name='新增用户数'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='users_deleted',
            field=models.IntegerField(default=0, verbose_name='删除用户数'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='users_moved',
            field=models.IntegerField(default=0, verbose_name='移动用户数'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='users_updated',
            field=models.IntegerField(default=0, verbose_name='更新用户数'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='sync_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='同步时间'),
        ),
    ]
