# Generated by Django 5.1.7 on 2025-03-23 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0011_synclog_departments_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synclog',
            name='departments_added',
        ),
        migrations.RemoveField(
            model_name='synclog',
            name='departments_deleted',
        ),
        migrations.RemoveField(
            model_name='synclog',
            name='departments_moved',
        ),
        migrations.RemoveField(
            model_name='synclog',
            name='departments_updated',
        ),
        migrations.RemoveField(
            model_name='synclog',
            name='detailed_logs',
        ),
        migrations.RemoveField(
            model_name='synclog',
            name='users_added',
        ),
        migrations.RemoveField(
            model_name='synclog',
            name='users_deleted',
        ),
        migrations.RemoveField(
            model_name='synclog',
            name='users_moved',
        ),
        migrations.RemoveField(
            model_name='synclog',
            name='users_updated',
        ),
        migrations.AlterField(
            model_name='synclog',
            name='sync_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='同步时间'),
        ),
    ]
