# Generated by Django 5.1.7 on 2025-03-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0012_remove_synclog_departments_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='detailed_logs',
            field=models.JSONField(blank=True, default=dict, verbose_name='详细操作日志'),
        ),
    ]
