# Generated by Django 5.1.7 on 2025-03-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0015_remove_synclog_message_alter_synclogdetail_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='message',
            field=models.TextField(blank=True, verbose_name='同步消息'),
        ),
        migrations.AlterField(
            model_name='synclogdetail',
            name='action',
            field=models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('move', '移动')], max_length=20, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='synclogdetail',
            name='object_type',
            field=models.CharField(choices=[('user', '用户'), ('department', '部门')], max_length=20, verbose_name='对象类型'),
        ),
    ]
