# Generated by Django 5.1.7 on 2025-03-23 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0016_synclog_message_alter_synclogdetail_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synclog',
            name='message',
        ),
    ]
