# Generated by Django 5.2 on 2025-04-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0017_remove_synclog_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syncconfig',
            name='sync_frequency',
        ),
        migrations.AddField(
            model_name='ldapconfig',
            name='sync_interval',
            field=models.IntegerField(default=300, verbose_name='同步间隔(秒)'),
        ),
        migrations.AddField(
            model_name='syncconfig',
            name='sync_interval',
            field=models.IntegerField(default=300, verbose_name='同步间隔(秒)'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='错误信息'),
        ),
    ]
