# Generated by Django 5.1.7 on 2025-03-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dingtalkconfig',
            name='fetch_users',
            field=models.BooleanField(default=True, verbose_name='是否获取用户列表'),
        ),
        migrations.AddField(
            model_name='dingtalkconfig',
            name='sync_enabled',
            field=models.BooleanField(default=True, verbose_name='是否同步'),
        ),
        migrations.AddField(
            model_name='feishuconfig',
            name='fetch_users',
            field=models.BooleanField(default=True, verbose_name='是否获取用户列表'),
        ),
        migrations.AddField(
            model_name='feishuconfig',
            name='sync_enabled',
            field=models.BooleanField(default=True, verbose_name='是否同步'),
        ),
        migrations.AddField(
            model_name='wecomconfig',
            name='fetch_users',
            field=models.BooleanField(default=True, verbose_name='是否获取用户列表'),
        ),
        migrations.AddField(
            model_name='wecomconfig',
            name='sync_enabled',
            field=models.BooleanField(default=True, verbose_name='是否同步'),
        ),
    ]
