# Generated by Django 5.1.7 on 2025-03-24 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0003_remove_dingtalkuser_user_remove_feishuuser_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dingtalk_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='feishu_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gitee_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='github_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gitlab_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wecom_user',
        ),
        migrations.AddField(
            model_name='dingtalkuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dingtalk_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feishuuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feishu_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wecomuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wecom_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='giteeuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gitee_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='github_user', to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
        migrations.AlterField(
            model_name='gitlabuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gitlab_user', to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
        migrations.AlterField(
            model_name='googleuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='google_user', to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
    ]
