# Generated by Django 5.2 on 2025-04-17 09:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0004_remove_user_dingtalk_user_remove_user_feishu_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wecomuser',
            name='department',
        ),
        migrations.CreateModel(
            name='WeComDepartments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='部门名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='oAuth.wecomdepartments', verbose_name='父级部门')),
            ],
            options={
                'verbose_name': '企业微信部门',
                'verbose_name_plural': '企业微信部门',
            },
        ),
    ]
