# Generated by Django 5.2 on 2025-04-17 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0005_remove_wecomuser_department_wecomdepartments'),
    ]

    operations = [
        migrations.AddField(
            model_name='wecomuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wecom_user', to='oAuth.wecomdepartments'),
        ),
    ]
