# Generated by Django 5.2 on 2025-04-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0006_wecomuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wecomuser',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='部门'),
        ),
        migrations.DeleteModel(
            name='WeComDepartments',
        ),
    ]
