# Generated by Django 5.2 on 2025-04-18 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0007_alter_wecomuser_department_delete_wecomdepartments'),
    ]

    operations = [
        migrations.AddField(
            model_name='wecomconfig',
            name='sync_time',
            field=models.TimeField(blank=True, help_text='每日定时同步的时间', null=True, verbose_name='同步时间'),
        ),
        migrations.RemoveField(
            model_name='wecomuser',
            name='department',
        ),
        migrations.CreateModel(
            name='WeComDepartment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='部门ID')),
                ('name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='oAuth.wecomdepartment', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '企业微信部门',
                'verbose_name_plural': '企业微信部门',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='wecomuser',
            name='department',
            field=models.ManyToManyField(blank=True, related_name='users', to='oAuth.wecomdepartment', verbose_name='部门'),
        ),
    ]
