# Generated by Django 5.2 on 2025-04-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0008_wecomconfig_sync_time_remove_wecomuser_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wecomuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='wecomconfig',
            name='sync_time',
        ),
        migrations.DeleteModel(
            name='WeComDepartment',
        ),
        migrations.AddField(
            model_name='wecomuser',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='部门'),
        ),
    ]
